name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This adds the manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
      working-directory: server

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: server

    - name: Run tests
      run: |
        source .venv/bin/activate
        python -m unittest discover -s __tests__ -v
      working-directory: server
